import 'package:uuid/uuid.dart';
import '../models/user_model.dart';
import '../models/product_model.dart';
import '../models/order_model.dart';
import '../models/goal_model.dart';

/// Demo data service that provides mock data for development
/// Replace with Supabase calls when backend is connected
class DemoData {
  static const _uuid = Uuid();

  static List<UserModel> get users => [
        UserModel(
          id: 'admin-001',
          name: 'Kutbi Admin',
          phone: '2222222222',
          email: 'admin@kutbipaints.com',
          pin: '7777',
          role: 'admin',
          status: 'active',
          businessName: 'Kutbi Hardware & Paints',
          businessAddress: 'Main Market, Gujarat',
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        UserModel(
          id: 'painter-001',
          name: 'Rajesh Kumar',
          phone: '0000000000',
          email: 'rajesh@gmail.com',
          pin: '5656',
          role: 'painter',
          status: 'active',
          businessName: 'Rajesh Painting Services',
          businessAddress: '12, Market Road, Ahmedabad',
          tier: 'gold',
          totalPurchaseValue: 125000,
          createdAt: DateTime(2024, 2, 15),
          updatedAt: DateTime(2024, 2, 15),
        ),
        UserModel(
          id: 'painter-002',
          name: 'Amit Sharma',
          phone: '1111111111',
          email: 'amit@gmail.com',
          pin: '5454',
          role: 'painter',
          status: 'active',
          businessName: 'Sharma Paint Works',
          businessAddress: '45, Gandhi Nagar, Surat',
          tier: 'silver',
          totalPurchaseValue: 45000,
          createdAt: DateTime(2024, 3, 10),
          updatedAt: DateTime(2024, 3, 10),
        ),
        UserModel(
          id: 'painter-003',
          name: 'Suresh Patel',
          phone: '9999999999',
          email: 'suresh@gmail.com',
          pin: '5858',
          role: 'painter',
          status: 'active',
          businessName: 'Patel Decorators',
          businessAddress: '78, Station Road, Vadodara',
          tier: 'silver',
          totalPurchaseValue: 78000,
          createdAt: DateTime(2024, 4, 5),
          updatedAt: DateTime(2024, 4, 5),
        ),
        UserModel(
          id: 'painter-004',
          name: 'Mohammed Ali',
          phone: '8888888888',
          email: 'ali@gmail.com',
          pin: '1234',
          role: 'painter',
          status: 'inactive',
          businessName: 'Ali Paint House',
          businessAddress: '23, Ring Road, Rajkot',
          createdAt: DateTime(2024, 5, 20),
          updatedAt: DateTime(2024, 5, 20),
        ),
      ];

  static List<ProductModel> get products => [
        // Asian Paints
        ProductModel(
          id: 'ap-001',
          name: 'Royale Luxury Emulsion',
          brand: 'Asian Paints',
          category: 'Interior Paints',
          subCategory: 'Luxury Emulsion',
          colorCode: 'AP-7840',
          colorName: 'Coral Red',
          colorHex: '#FF6F61',
          description: 'Premium silk finish emulsion with superior coverage',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 450, '4L': 1650, '10L': 3900, '20L': 7200},
          goldPrices: {'1L': 420, '4L': 1540, '10L': 3650, '20L': 6750},
          stockLevel: 150,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'ap-002',
          name: 'Apex Ultima Weather Proof',
          brand: 'Asian Paints',
          category: 'Exterior Paints',
          subCategory: 'Weather Proof',
          colorCode: 'AP-2150',
          colorName: 'Sky Blue',
          colorHex: '#87CEEB',
          description: 'Exterior weather-proof paint with 7-year warranty',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 380, '4L': 1400, '10L': 3300, '20L': 6100},
          goldPrices: {'1L': 355, '4L': 1310, '10L': 3080, '20L': 5700},
          stockLevel: 85,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'ap-003',
          name: 'Tractor Emulsion',
          brand: 'Asian Paints',
          category: 'Interior Paints',
          subCategory: 'Economical Emulsion',
          colorCode: 'AP-0501',
          colorName: 'Ivory White',
          colorHex: '#FFFFF0',
          description: 'Economical interior emulsion paint',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 180, '4L': 650, '10L': 1500, '20L': 2800},
          goldPrices: {'1L': 168, '4L': 607, '10L': 1400, '20L': 2615},
          stockLevel: 200,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'ap-004',
          name: 'Royale Play Ragging',
          brand: 'Asian Paints',
          category: 'Interior Paints',
          subCategory: 'Textures',
          colorCode: 'AP-9623',
          colorName: 'Dusty Rose',
          colorHex: '#DCAE96',
          description: 'Textured finish with premium metallic effect',
          bucketSizes: ['1L', '4L'],
          prices: {'1L': 650, '4L': 2400},
          goldPrices: {'1L': 605, '4L': 2240},
          stockLevel: 45,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'ap-005',
          name: 'SmartCare Damp Proof',
          brand: 'Asian Paints',
          category: 'Waterproofing',
          subCategory: 'Damp Proof',
          colorCode: 'AP-1100',
          colorName: 'White',
          colorHex: '#FFFFFF',
          description: 'Waterproofing solution for walls',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 520, '4L': 1900, '10L': 4500, '20L': 8200},
          goldPrices: {'1L': 485, '4L': 1770, '10L': 4200, '20L': 7650},
          stockLevel: 8,
          lowStockThreshold: 10,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),

        // Berger
        ProductModel(
          id: 'bg-001',
          name: 'Silk Glamour',
          brand: 'Berger',
          category: 'Interior Paints',
          subCategory: 'Luxury Emulsion',
          colorCode: 'BG-4520',
          colorName: 'Sunset Orange',
          colorHex: '#FD5E53',
          description: 'Ultra-smooth silk finish with anti-bacterial properties',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 420, '4L': 1550, '10L': 3650, '20L': 6800},
          goldPrices: {'1L': 392, '4L': 1445, '10L': 3405, '20L': 6350},
          stockLevel: 120,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'bg-002',
          name: 'WeatherCoat All Guard',
          brand: 'Berger',
          category: 'Exterior Paints',
          subCategory: 'Weather Proof',
          colorCode: 'BG-3210',
          colorName: 'Mint Green',
          colorHex: '#98FB98',
          description: 'Advanced exterior paint with 10-year protection',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 400, '4L': 1480, '10L': 3500, '20L': 6500},
          goldPrices: {'1L': 372, '4L': 1378, '10L': 3260, '20L': 6060},
          stockLevel: 95,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'bg-003',
          name: 'Bison Acrylic Distemper',
          brand: 'Berger',
          category: 'Interior Paints',
          subCategory: 'Distemper',
          colorCode: 'BG-1001',
          colorName: 'Off White',
          colorHex: '#FAF0E6',
          description: 'Budget-friendly acrylic distemper',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 120, '4L': 420, '10L': 980, '20L': 1800},
          goldPrices: {'1L': 112, '4L': 392, '10L': 915, '20L': 1680},
          stockLevel: 300,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'bg-004',
          name: 'Express Painting Primer',
          brand: 'Berger',
          category: 'Primers',
          subCategory: 'Interior Primer',
          colorCode: 'BG-0100',
          colorName: 'White Primer',
          colorHex: '#F5F5F5',
          description: 'Quick-dry primer for interior walls',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 280, '4L': 1000, '10L': 2350, '20L': 4400},
          goldPrices: {'1L': 261, '4L': 932, '10L': 2190, '20L': 4100},
          stockLevel: 5,
          lowStockThreshold: 10,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),

        // Birla Opus
        ProductModel(
          id: 'bo-002',
          name: 'Shield Exterior Emulsion',
          brand: 'Birla Opus',
          category: 'Exterior Paints',
          subCategory: 'Weather Proof',
          colorCode: 'BO-2350',
          colorName: 'Sandstone',
          colorHex: '#C2B280',
          description: 'Weather resistant exterior emulsion',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 390, '4L': 1440, '10L': 3400, '20L': 6300},
          goldPrices: {'1L': 363, '4L': 1342, '10L': 3170, '20L': 5878},
          stockLevel: 110,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'bo-003',
          name: 'Natura Health Plus',
          brand: 'Birla Opus',
          category: 'Interior Paints',
          subCategory: 'Health Plus',
          colorCode: 'BO-5080',
          colorName: 'Ocean Blue',
          colorHex: '#4169E1',
          description: 'Low-VOC anti-bacterial paint for healthy homes',
          bucketSizes: ['1L', '4L', '10L'],
          prices: {'1L': 550, '4L': 2000, '10L': 4700},
          goldPrices: {'1L': 512, '4L': 1860, '10L': 4380},
          stockLevel: 60,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
        ProductModel(
          id: 'bo-004',
          name: 'Opus Primer',
          brand: 'Birla Opus',
          category: 'Primers',
          subCategory: 'Premium Primer',
          colorCode: 'BO-0010',
          colorName: 'White Base',
          colorHex: '#FAFAFA',
          description: 'Premium water-based primer',
          bucketSizes: ['1L', '4L', '10L', '20L'],
          prices: {'1L': 300, '4L': 1080, '10L': 2550, '20L': 4750},
          goldPrices: {'1L': 280, '4L': 1008, '10L': 2378, '20L': 4430},
          stockLevel: 3,
          lowStockThreshold: 10,
          createdAt: DateTime(2024, 1, 1),
          updatedAt: DateTime(2024, 1, 1),
        ),
      ];

  static List<OrderModel> get orders => [
        OrderModel(
          id: 'order-001',
          painterId: 'painter-001',
          brand: 'Asian Paints',
          items: [
            OrderItemModel(
              productId: 'ap-001',
              productName: 'Royale Luxury Emulsion',
              colorCode: 'AP-7840',
              colorName: 'Coral Red',
              colorHex: '#FF6F61',
              quantity: 5,
              bucketSize: '10L',
              unitPrice: 3650,
              totalPrice: 18250,
            ),
            OrderItemModel(
              productId: 'ap-003',
              productName: 'Tractor Emulsion',
              colorCode: 'AP-0501',
              colorName: 'Ivory White',
              colorHex: '#FFFFF0',
              quantity: 10,
              bucketSize: '20L',
              unitPrice: 2615,
              totalPrice: 26150,
            ),
          ],
          siteLocation: '23, New Colony, Ahmedabad',
          siteLat: 23.0225,
          siteLng: 72.5714,
          paymentMethod: 'cod',
          totalAmount: 44400,
          status: 'delivered',
          createdAt: DateTime.now().subtract(const Duration(days: 15)),
          updatedAt: DateTime.now().subtract(const Duration(days: 12)),
        ),
        OrderModel(
          id: 'order-002',
          painterId: 'painter-001',
          brand: 'Berger',
          items: [
            OrderItemModel(
              productId: 'bg-001',
              productName: 'Silk Glamour',
              colorCode: 'BG-4520',
              colorName: 'Sunset Orange',
              colorHex: '#FD5E53',
              quantity: 3,
              bucketSize: '4L',
              unitPrice: 1445,
              totalPrice: 4335,
            ),
          ],
          siteLocation: '56, Ring Road, Ahmedabad',
          siteLat: 23.0300,
          siteLng: 72.5800,
          paymentMethod: 'online',
          totalAmount: 4335,
          status: 'dispatched',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
          updatedAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        OrderModel(
          id: 'order-003',
          painterId: 'painter-002',
          brand: 'Birla Opus',
          items: [
            OrderItemModel(
              productId: 'bo-002',
              productName: 'Shield Exterior Emulsion',
              colorCode: 'BO-2350',
              colorName: 'Sandstone',
              colorHex: '#C2B280',
              quantity: 2,
              bucketSize: '10L',
              unitPrice: 3400,
              totalPrice: 6800,
            ),
          ],
          siteLocation: '12, Garden Area, Surat',
          siteLat: 21.1702,
          siteLng: 72.8311,
          paymentMethod: 'cod',
          totalAmount: 8400,
          status: 'preparing',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
          updatedAt: DateTime.now(),
        ),
        OrderModel(
          id: 'order-004',
          painterId: 'painter-003',
          brand: 'Asian Paints',
          items: [
            OrderItemModel(
              productId: 'ap-002',
              productName: 'Apex Ultima Weather Proof',
              colorCode: 'AP-2150',
              colorName: 'Sky Blue',
              colorHex: '#87CEEB',
              quantity: 8,
              bucketSize: '20L',
              unitPrice: 6100,
              totalPrice: 48800,
            ),
          ],
          siteLocation: '89, Industrial Area, Vadodara',
          siteLat: 22.3072,
          siteLng: 73.1812,
          paymentMethod: 'cod',
          totalAmount: 48800,
          status: 'placed',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
      ];

  static List<GoalModel> get goals => [
        // Berger - 3 stages
        GoalModel(
          id: 'goal-b1',
          title: 'Berger Starter',
          description: 'Buy 20 buckets of Berger products',
          brand: 'Berger',
          targetQuantity: 20,
          rewardAmount: 100,
          assignedTo: ['all'],
          startDate: DateTime.now().subtract(const Duration(days: 30)),
          endDate: DateTime.now().add(const Duration(days: 60)),
          createdAt: DateTime.now().subtract(const Duration(days: 30)),
        ),
        GoalModel(
          id: 'goal-b2',
          title: 'Berger Champion',
          description: 'Buy 50 buckets of Berger products',
          brand: 'Berger',
          targetQuantity: 50,
          rewardAmount: 300,
          assignedTo: ['all'],
          startDate: DateTime.now().subtract(const Duration(days: 30)),
          endDate: DateTime.now().add(const Duration(days: 60)),
          createdAt: DateTime.now().subtract(const Duration(days: 30)),
        ),
        GoalModel(
          id: 'goal-b3',
          title: 'Berger Master',
          description: 'Buy 100 buckets of Berger products',
          brand: 'Berger',
          targetQuantity: 100,
          rewardAmount: 500,
          assignedTo: ['all'],
          startDate: DateTime.now().subtract(const Duration(days: 30)),
          endDate: DateTime.now().add(const Duration(days: 60)),
          createdAt: DateTime.now().subtract(const Duration(days: 30)),
        ),
        // Asian Paints - 3 stages
        GoalModel(
          id: 'goal-a1',
          title: 'Asian Paints Beginner',
          description: 'Order 15 buckets of Asian Paints',
          brand: 'Asian Paints',
          targetQuantity: 15,
          rewardAmount: 80,
          assignedTo: ['all'],
          startDate: DateTime.now().subtract(const Duration(days: 15)),
          endDate: DateTime.now().add(const Duration(days: 45)),
          createdAt: DateTime.now().subtract(const Duration(days: 15)),
        ),
        GoalModel(
          id: 'goal-a2',
          title: 'Asian Paints Pro',
          description: 'Order 30 buckets of Asian Paints Royale range',
          brand: 'Asian Paints',
          targetQuantity: 30,
          rewardAmount: 200,
          assignedTo: ['painter-001', 'painter-002'],
          startDate: DateTime.now().subtract(const Duration(days: 15)),
          endDate: DateTime.now().add(const Duration(days: 45)),
          createdAt: DateTime.now().subtract(const Duration(days: 15)),
        ),
        GoalModel(
          id: 'goal-a3',
          title: 'Asian Paints Elite',
          description: 'Order 60 buckets of Asian Paints',
          brand: 'Asian Paints',
          targetQuantity: 60,
          rewardAmount: 500,
          assignedTo: ['all'],
          startDate: DateTime.now().subtract(const Duration(days: 15)),
          endDate: DateTime.now().add(const Duration(days: 45)),
          createdAt: DateTime.now().subtract(const Duration(days: 15)),
        ),
        // Birla Opus - 2 stages
        GoalModel(
          id: 'goal-bo1',
          title: 'Birla Opus Starter',
          description: 'Buy 10 buckets of Birla Opus',
          brand: 'Birla Opus',
          targetQuantity: 10,
          rewardAmount: 50,
          rewardType: 'discount',
          assignedTo: ['all'],
          startDate: DateTime.now(),
          endDate: DateTime.now().add(const Duration(days: 90)),
          createdAt: DateTime.now(),
        ),
        GoalModel(
          id: 'goal-bo2',
          title: 'Birla Opus Star',
          description: 'Buy 30 buckets of Birla Opus',
          brand: 'Birla Opus',
          targetQuantity: 30,
          rewardAmount: 200,
          rewardType: 'discount',
          assignedTo: ['all'],
          startDate: DateTime.now(),
          endDate: DateTime.now().add(const Duration(days: 90)),
          createdAt: DateTime.now(),
        ),
      ];

  static List<RewardModel> get rewards => [
        RewardModel(
          id: 'reward-001',
          painterId: 'painter-001',
          goalId: 'goal-old-001',
          rewardAmount: 500,
          status: 'redeemed',
          earnedAt: DateTime.now().subtract(const Duration(days: 60)),
        ),
        RewardModel(
          id: 'reward-002',
          painterId: 'painter-001',
          goalId: 'goal-old-002',
          rewardAmount: 200,
          status: 'earned',
          earnedAt: DateTime.now().subtract(const Duration(days: 20)),
        ),
      ];
}
