import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:http/http.dart' as http;
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../core/constants/app_colors.dart';
import '../../core/utils/responsive.dart';
import '../../models/return_model.dart';
import '../../services/data_service.dart';

// ============================================================================
// ReturnTrackingScreen — vertical timeline showing full lifecycle
// ============================================================================
class ReturnTrackingScreen extends ConsumerWidget {
  final String returnId;
  const ReturnTrackingScreen({super.key, required this.returnId});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final ds = ref.watch(dataServiceProvider);
    final returnRequest = ds.getReturnRequestById(returnId);

    if (returnRequest == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Track Return')),
        body: const Center(child: Text('Return request not found.')),
      );
    }

    final order = ds.getOrderById(returnRequest.orderId);
    final isActive = !returnRequest.status.isTerminal;

    return Scaffold(
      backgroundColor: AppColors.scaffoldBg,
      appBar: AppBar(
        backgroundColor: Colors.white,
        foregroundColor: AppColors.textPrimary,
        elevation: 0,
        centerTitle: true,
        title: Text(
          returnRequest.displayId,
          style: GoogleFonts.poppins(fontWeight: FontWeight.w600),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded),
          onPressed: () {
            if (context.canPop()) {
              context.pop();
            } else {
              context.go('/painter/my-returns');
            }
          },
        ),
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.symmetric(
          horizontal: Responsive.horizontalPadding(context),
          vertical: 20,
        ),
        child: Center(
          child: ConstrainedBox(
            constraints: BoxConstraints(maxWidth: Responsive.contentMaxWidth(context)),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
            // Header card
            _HeaderCard(returnRequest: returnRequest, order: order),
            const SizedBox(height: 20),

            // Return Bill / Credit Note (if generated by admin)
            if (returnRequest.billUrl != null && returnRequest.billUrl!.isNotEmpty) ...[
              _ReturnBillCard(returnRequest: returnRequest),
              const SizedBox(height: 20),
            ],

            // Items
            if (returnRequest.items.isNotEmpty) ...[
              _ItemsCard(returnRequest: returnRequest),
              const SizedBox(height: 20),
            ],

            // Timeline
            _buildTimeline(returnRequest),
            const SizedBox(height: 20),

            // Admin note / rejection reason
            if (returnRequest.cleanAdminNote != null &&
                returnRequest.cleanAdminNote!.isNotEmpty) ...[
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: returnRequest.status == ReturnStatus.rejected
                      ? AppColors.error.withValues(alpha: 0.06)
                      : AppColors.info.withValues(alpha: 0.06),
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(
                    color: returnRequest.status == ReturnStatus.rejected
                        ? AppColors.error.withValues(alpha: 0.25)
                        : AppColors.info.withValues(alpha: 0.25),
                  ),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      returnRequest.status == ReturnStatus.rejected
                          ? 'Rejection Reason'
                          : 'Admin Note',
                      style: GoogleFonts.poppins(
                        fontSize: 12,
                        fontWeight: FontWeight.w700,
                        color: returnRequest.status == ReturnStatus.rejected
                            ? AppColors.error
                            : AppColors.info,
                      ),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      returnRequest.cleanAdminNote!,
                      style: GoogleFonts.poppins(
                        fontSize: 13,
                        color: AppColors.textPrimary,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 20),
            ],

            // Cancel button (if eligible)
            if (isActive && returnRequest.status.canBeCancelledByUser)
              _CancelButton(returnId: returnId),

            const SizedBox(height: 40),
          ],
        ),
      ),
    ),
  ),
);
  }

  Widget _buildTimeline(ReturnRequestModel r) {
    final steps = _buildTimelineSteps(r);

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Return Timeline',
            style: GoogleFonts.poppins(
              fontSize: 13,
              fontWeight: FontWeight.w700,
              color: AppColors.textSecondary,
            ),
          ),
          const SizedBox(height: 16),
          ...steps.asMap().entries.map((entry) {
            final i = entry.key;
            final step = entry.value;
            final isLast = i == steps.length - 1;
            return _TimelineRow(
              step: step,
              showLine: !isLast,
            );
          }),
        ],
      ),
    );
  }

  List<_TimelineStep> _buildTimelineSteps(ReturnRequestModel r) {
    // For rejected returns: show up to rejected step
    if (r.status == ReturnStatus.rejected) {
      return [
        _TimelineStep(
          label: 'Return Requested',
          timestamp: r.requestedAt,
          isDone: true,
          icon: Icons.assignment_return_rounded,
        ),
        _TimelineStep(
          label: 'Return Rejected',
          timestamp: r.rejectedAt ?? r.updatedAt,
          isDone: true,
          icon: Icons.cancel_rounded,
          color: AppColors.error,
        ),
      ];
    }

    // For cancelled: show up to cancelled step
    if (r.status == ReturnStatus.cancelled) {
      return [
        _TimelineStep(
          label: 'Return Requested',
          timestamp: r.requestedAt,
          isDone: true,
          icon: Icons.assignment_return_rounded,
        ),
        _TimelineStep(
          label: 'Cancelled',
          timestamp: r.updatedAt,
          isDone: true,
          icon: Icons.do_not_disturb_on_rounded,
          color: AppColors.textSecondary,
        ),
      ];
    }

    // Normal forward flow
    final ordered = [
      ReturnStatus.requested,
      ReturnStatus.approved,
      ReturnStatus.pickupScheduled,
      ReturnStatus.pickedUp,
      ReturnStatus.received,
      ReturnStatus.refundProcessing,
      ReturnStatus.refunded,
    ];

    final currentIdx = ordered.indexOf(r.status);

    return [
      _TimelineStep(
        label: 'Return Requested',
        timestamp: r.requestedAt,
        isDone: true,
        icon: Icons.assignment_return_rounded,
      ),
      _TimelineStep(
        label: 'Return Approved',
        timestamp: r.approvedAt,
        isDone: currentIdx >= 1,
        icon: Icons.check_circle_rounded,
      ),
      _TimelineStep(
        label: 'Pickup Scheduled',
        timestamp: r.pickupScheduledAt,
        isDone: currentIdx >= 2,
        icon: Icons.local_shipping_rounded,
      ),
      _TimelineStep(
        label: 'Product Picked Up',
        timestamp: r.pickedUpAt,
        isDone: currentIdx >= 3,
        icon: Icons.inventory_2_rounded,
      ),
      _TimelineStep(
        label: 'Product Received',
        timestamp: r.receivedAt,
        isDone: currentIdx >= 4,
        icon: Icons.warehouse_rounded,
      ),
      _TimelineStep(
        label: 'Refund Processing',
        timestamp: r.refundProcessingAt,
        isDone: currentIdx >= 5,
        icon: Icons.account_balance_wallet_rounded,
        color: currentIdx >= 5 ? const Color(0xFF8B5CF6) : null,
      ),
      _TimelineStep(
        label: 'Refund Completed',
        timestamp: r.refundedAt,
        isDone: currentIdx >= 6,
        icon: Icons.celebration_rounded,
        color: currentIdx >= 6 ? AppColors.success : null,
      ),
    ];
  }
}

// ─── Header card ──────────────────────────────────────────────────────────────

class _HeaderCard extends StatelessWidget {
  final ReturnRequestModel returnRequest;
  final dynamic order;

  const _HeaderCard({required this.returnRequest, required this.order});

  @override
  Widget build(BuildContext context) {
    final statusColor = _statusColor(returnRequest.status);
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                returnRequest.displayId,
                style: GoogleFonts.poppins(
                  fontSize: 15,
                  fontWeight: FontWeight.w700,
                  color: AppColors.textPrimary,
                ),
              ),
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 5),
                decoration: BoxDecoration(
                  color: statusColor.withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(color: statusColor.withValues(alpha: 0.3)),
                ),
                child: Text(
                  returnRequest.status.label,
                  style: GoogleFonts.poppins(
                    fontSize: 11,
                    fontWeight: FontWeight.w700,
                    color: statusColor,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          if (order != null) ...[
            _infoRow('Order', '#${order.id.substring(0, 8).toUpperCase()}'),
            _infoRow('Brand', order.brand ?? '-'),
          ],
          _infoRow('Reason', returnRequest.reason),
          _infoRow(
            'Requested',
            DateFormat('dd MMM yyyy').format(returnRequest.requestedAt),
          ),
          if (returnRequest.refundAmount > 0)
            _infoRow(
              'Refund Amount',
              '₹${returnRequest.refundAmount.toStringAsFixed(0)}',
            ),
        ],
      ),
    );
  }

  Widget _infoRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        children: [
          SizedBox(
            width: 100,
            child: Text(
              label,
              style: GoogleFonts.poppins(
                fontSize: 12,
                color: AppColors.textSecondary,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: GoogleFonts.poppins(
                fontSize: 12,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

Color _statusColor(ReturnStatus status) {
  switch (status) {
    case ReturnStatus.requested:
      return AppColors.warning;
    case ReturnStatus.approved:
      return AppColors.info;
    case ReturnStatus.pickupScheduled:
    case ReturnStatus.pickedUp:
    case ReturnStatus.received:
      return AppColors.info;
    case ReturnStatus.refundProcessing:
      return const Color(0xFF8B5CF6);
    case ReturnStatus.refunded:
      return AppColors.success;
    case ReturnStatus.rejected:
      return AppColors.error;
    case ReturnStatus.cancelled:
      return AppColors.textSecondary;
  }
}

// ─── Items card ───────────────────────────────────────────────────────────────

class _ItemsCard extends StatelessWidget {
  final ReturnRequestModel returnRequest;
  const _ItemsCard({required this.returnRequest});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.grey.shade200),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Returned Items',
            style: GoogleFonts.poppins(
              fontSize: 13,
              fontWeight: FontWeight.w700,
              color: AppColors.textSecondary,
            ),
          ),
          const SizedBox(height: 12),
          ...returnRequest.items.map((item) => Padding(
                padding: const EdgeInsets.only(bottom: 12),
                child: Row(
                  children: [
                    Container(
                      width: 36,
                      height: 36,
                      decoration: BoxDecoration(
                        color: _colorFromHex(item.colorHex ?? '#1565C0')
                            .withValues(alpha: 0.15),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Icon(
                        Icons.format_paint_rounded,
                        size: 18,
                        color: _colorFromHex(item.colorHex ?? '#1565C0'),
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            item.productName,
                            style: GoogleFonts.poppins(
                              fontSize: 13,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                          Text(
                            '${item.bucketSize} · ${item.colorName ?? ""} · Qty: ${item.quantity}',
                            style: GoogleFonts.poppins(
                              fontSize: 11,
                              color: AppColors.textSecondary,
                            ),
                          ),
                        ],
                      ),
                    ),
                    Text(
                      item.unitPrice > 0
                          ? '₹${item.totalPrice.toStringAsFixed(0)}'
                          : '-',
                      style: GoogleFonts.poppins(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              )),
        ],
      ),
    );
  }

  Color _colorFromHex(String hex) {
    try {
      return Color(int.parse(hex.replaceFirst('#', '0xFF')));
    } catch (_) {
      return AppColors.primary;
    }
  }
}

// ─── Timeline row ─────────────────────────────────────────────────────────────

class _TimelineStep {
  final String label;
  final DateTime? timestamp;
  final bool isDone;
  final IconData icon;
  final Color? color;

  const _TimelineStep({
    required this.label,
    required this.timestamp,
    required this.isDone,
    required this.icon,
    this.color,
  });
}

class _TimelineRow extends StatelessWidget {
  final _TimelineStep step;
  final bool showLine;

  const _TimelineRow({required this.step, required this.showLine});

  @override
  Widget build(BuildContext context) {
    final activeColor =
        step.color ?? (step.isDone ? AppColors.success : Colors.grey.shade300);

    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Column(
          children: [
            Container(
              width: 36,
              height: 36,
              decoration: BoxDecoration(
                color: step.isDone
                    ? activeColor.withValues(alpha: 0.12)
                    : Colors.grey.shade100,
                shape: BoxShape.circle,
                border: Border.all(
                  color: step.isDone ? activeColor : Colors.grey.shade300,
                  width: 1.5,
                ),
              ),
              child: Icon(
                step.icon,
                size: 18,
                color: step.isDone ? activeColor : Colors.grey.shade400,
              ),
            ),
            if (showLine)
              Container(
                width: 2,
                height: 40,
                color: step.isDone
                    ? activeColor.withValues(alpha: 0.3)
                    : Colors.grey.shade200,
              ),
          ],
        ),
        const SizedBox(width: 14),
        Expanded(
          child: Padding(
            padding: EdgeInsets.only(bottom: showLine ? 12 : 0, top: 6),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  step.label,
                  style: GoogleFonts.poppins(
                    fontSize: 13,
                    fontWeight:
                        step.isDone ? FontWeight.w600 : FontWeight.w400,
                    color: step.isDone
                        ? AppColors.textPrimary
                        : AppColors.textLight,
                  ),
                ),
                if (step.timestamp != null && step.isDone) ...[
                  const SizedBox(height: 2),
                  Text(
                    DateFormat('dd MMM yyyy, hh:mm a')
                        .format(step.timestamp!),
                    style: GoogleFonts.poppins(
                      fontSize: 11,
                      color: AppColors.textSecondary,
                    ),
                  ),
                ],
              ],
            ),
          ),
        ),
      ],
    );
  }
}

// ─── Cancel button ────────────────────────────────────────────────────────────

class _CancelButton extends ConsumerStatefulWidget {
  final String returnId;
  const _CancelButton({required this.returnId});

  @override
  ConsumerState<_CancelButton> createState() => _CancelButtonState();
}

class _CancelButtonState extends ConsumerState<_CancelButton> {
  bool _loading = false;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.infinity,
      child: OutlinedButton(
        onPressed: _loading ? null : _cancel,
        style: OutlinedButton.styleFrom(
          foregroundColor: AppColors.error,
          side: const BorderSide(color: AppColors.error),
          padding: const EdgeInsets.symmetric(vertical: 14),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(14),
          ),
        ),
        child: Text(
          _loading ? 'Cancelling…' : 'Cancel Return Request',
          style: GoogleFonts.poppins(fontWeight: FontWeight.w600),
        ),
      ),
    );
  }

  Future<void> _cancel() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (_) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: Text('Cancel Return',
            style: GoogleFonts.poppins(fontWeight: FontWeight.w700)),
        content: Text('Are you sure you want to cancel this return request?',
            style: GoogleFonts.poppins()),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text('No', style: GoogleFonts.poppins()),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(backgroundColor: AppColors.error),
            child: Text('Yes, Cancel',
                style: GoogleFonts.poppins(color: Colors.white)),
          ),
        ],
      ),
    );

    if (confirmed != true || !mounted) return;

    setState(() => _loading = true);
    try {
      await ref.read(dataServiceProvider).cancelReturnRequest(widget.returnId);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Return cancelled.', style: GoogleFonts.poppins()),
            backgroundColor: AppColors.success,
          ),
        );
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: $e', style: GoogleFonts.poppins()),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }
}

// ─── Return Bill Card ─────────────────────────────────────────────────────────

class _ReturnBillCard extends StatefulWidget {
  final ReturnRequestModel returnRequest;
  const _ReturnBillCard({required this.returnRequest});

  @override
  State<_ReturnBillCard> createState() => _ReturnBillCardState();
}

class _ReturnBillCardState extends State<_ReturnBillCard> {
  bool _isLoading = false;

  Future<void> _openBill() async {
    final url = widget.returnRequest.billUrl;
    if (url == null || url.isEmpty) return;

    setState(() => _isLoading = true);
    try {
      final uri = Uri.parse(url);
      final res = await http.get(uri);
      if (res.statusCode == 200) {
        await Printing.layoutPdf(
          onLayout: (_) => res.bodyBytes,
          name: 'Return_Bill_${widget.returnRequest.displayId}.pdf',
        );
        return;
      }
    } catch (_) {
      // Fallback below
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }

    try {
      final uri = Uri.parse(url);
      if (await canLaunchUrl(uri)) {
        await launchUrl(uri, mode: LaunchMode.externalApplication);
      }
    } catch (_) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Could not open bill PDF', style: GoogleFonts.poppins()),
            backgroundColor: AppColors.error,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final req = widget.returnRequest;

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF7C3AED).withValues(alpha: 0.05),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: const Color(0xFF7C3AED).withValues(alpha: 0.3),
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: const Color(0xFF7C3AED).withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: const Icon(
                  Icons.receipt_long_rounded,
                  color: Color(0xFF7C3AED),
                  size: 24,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Return Bill / Credit Note',
                      style: GoogleFonts.poppins(
                        fontSize: 14,
                        fontWeight: FontWeight.w700,
                        color: const Color(0xFF7C3AED),
                      ),
                    ),
                    Text(
                      req.refundAmount > 0
                          ? 'Approved Refund: ₹${req.refundAmount.toStringAsFixed(0)}'
                          : 'Official Return Invoice Available',
                      style: GoogleFonts.poppins(
                        fontSize: 12,
                        color: AppColors.textSlateLight,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: _isLoading ? null : _openBill,
              icon: _isLoading
                  ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: Colors.white,
                      ),
                    )
                  : const Icon(Icons.download_rounded, size: 18),
              label: Text(
                _isLoading ? 'Loading Bill…' : 'View / Download Return Bill',
                style: GoogleFonts.poppins(
                  fontWeight: FontWeight.w600,
                  fontSize: 13,
                ),
              ),
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF7C3AED),
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 12),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

